apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ayakaleaf-pro
  namespace: argocd
spec:
  project: ayakaleaf-pro
  source:
    repoURL: https://github.com/Honahec/ayakaleaf-pro.git
    targetRevision: server-pro
    path: deploy/andromeda
  destination:
    server: https://kubernetes.default.svc
    namespace: ayakaleaf-pro
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
