apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ayakaleaf-pro
resources:
  - storage.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: ayakaleaf-pro-bootstrap
    files:
      - bootstrap/ensure-secrets.sh
      - bootstrap/mongo-ready.js
      - bootstrap/docker-ready.sh
      - bootstrap/daemon.json
images:
  - name: ghcr.io/honahec/ayakaleaf-pro
    digest: sha256:6d2e2efd264e43214e0f4c5b4509dd864757f5b8449f3783c97eec1345ff81a2
