apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ayakaleaf-pro
resources:
  - storage.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: ayakaleaf-pro-bootstrap
    files:
      - bootstrap/ensure-secrets.sh
      - bootstrap/mongo-ready.js
      - bootstrap/docker-ready.sh
      - bootstrap/daemon.json
images:
  - name: ghcr.io/honahec/ayakaleaf-pro
    digest: sha256:0138a2b84ce7038790fda647f58b1804a2b43b041bc24d57d061264ae66c997e
