apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ayakaleaf-pro
resources:
  - storage.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: ayakaleaf-pro-bootstrap
    files:
      - bootstrap/ensure-secrets.sh
      - bootstrap/mongo-ready.js
      - bootstrap/docker-ready.sh
      - bootstrap/daemon.json
images:
  - name: ghcr.io/honahec/ayakaleaf-pro
    digest: sha256:130e1acb2d6de2f8416646eea579decb7c094aa0160dc01baaa3f0b5bb95d370
