apiVersion: v1
kind: Service
metadata:
  name: ayakaleaf-pro
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ayakaleaf-pro
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
